server:
  port: 8801

spring:
  application:
    name: lylh
    version: @project.version@
  profiles:
    debug: true
    active: idea
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baselineOnMigrate: true
  jackson:
    property-naming-strategy: SNAKE_CASE #jackson全局转为下划线，参照PropertyNamingStrategy.class

lylh:
  auth:
    verifyToken: true


mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lylh.repository.entity